### ISSUE TITLE
Escaping @ character in the where clause

### ISSUE THREAD

**Issue by jgiovaresco** [r2dbc/r2dbc-mssql#201] opened 2021-04-29 07:31 UTC
#### Versions

- Driver: spring-data-r2dbc@1.3.0 / r2dbc-mssql@0.8.5.RELEASE /  mssql-jdbc@9.2.1.jre11
- Database: SQLServer 2017
- Java: 11
- OS: Mac OS

#### Current Behavior

Running a query using `DatabaseClient.sql()` which contains an `@` in the WHERE clause raises a `No parameters bound` error.

I tried to escape the character with `[]`: `SELECT * FROM users WHERE email = 'name[@]gmail.com'`
but the result is the same.

<details>
<summary>Stack trace</summary>

```
Caused by: java.lang.IllegalStateException: No parameters bound for query 'SELECT * from users WHERE email ='name@gmail.com''
```

</details>
 
#### Table schema

<details>
<summary>Input Code</summary>

```sql
create table users
(
    id                 nvarchar(255) not null constraint users_pk  primary key,
    username   nvarchar(255) not null,
    password    nvarchar(255) not null,
    email           nvarchar(255) not null
)
```

</details>

#### Steps to reproduce

<details>
<summary>Input Code</summary>

```java
template
            .getDatabaseClient()
            .sql("SELECT * FROM users WHERE email = 'name@gmail.com'")
            .map(JdbcUser::fromRow)
            .all()
```

</details>

#### Expected behavior/code

I'm expecting to run a query containing an escaped `@`

#### Possible Solution

It seems related to how we detect if a query is parameterized or not: https://github.com/r2dbc/r2dbc-mssql/blob/5868d7354c8701bf4b17c63c9570062bacd9d0be/src/main/java/io/r2dbc/mssql/ParametrizedMssqlStatement.java#L318
Maybe we could check if the `@` is escaped around there 🤔

**Comment by mp911de** [comment] 2021-04-29 08:27
Actually, the driver should not fail when a parameter isn't bound during `execute()` since we don't have a proper parser and the server-side reporting missing bindings should be fine. That's also what the JDBC driver does.

**Comment by mp911de** [comment] 2021-05-05 07:04
Duplicate of #197.

**Closed by mp911de** 2021-05-05 07:04 UTC
Labels: status: duplicate
