### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Chaithra60821** [r2dbc/r2dbc-mssql#89] opened 2019-08-28 01:59 UTC
HI 

I am facing issue when i am executing query with 60 columns data. throws the exception that 
connection disconnected by the peer. My query is a upsert query 

Sample query : 
```sql
String UPDATE_QUERY  = IF NOT EXISTS (SELECT * FROM SAMPL1 where dbo.PRIMARY_col = @PRIMARY_col)
          INSERT INTO col1, col2, col3)
          VALUES(@col1, @col2, @c0l3)
          ELSE
          UPDATE dbo.SAMPL1
          SET col1=@col1, col2 = @col2, col3=@col3
```

```java
Mono<Connection> connection1 = pool.create();
        connection1.flatMap(connection -> {
            Statement statement = connection.createStatement(UPDATE_QUERY);
            statement.bind("key", "value");
            //bind all the statements
            return Mono.just(statement);
        }).flatMap(statement -> Mono.from(statement.execute()))
                .flatMap(result -> result.getRowsUpdated()).susbscribe();
```

To reproduce the issue please add 60 column. When i execute the same query with 15 columns it works fine. If my query has 60 columns it fails with below error.
```
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1125)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mp911de** [comment] 2019-09-02 14:45
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by Chaithra60821** [comment] 2019-09-03 18:35
I have updated the comment and provided the same query and code.

**Comment by mp911de** [comment] 2019-09-18 09:59
I wasn't able to reproduce `Connection reset by peer`, however having a lot of columns can cause the column metadata frame to be fragmented and that can cause subsequent decoding issues.

Therefore we added a `canDecode(…)` check to prevent out of bounds index access.

**Comment by mp911de** [comment] 2019-09-23 12:27
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2019-09-23 12:27 UTC
Labels: status: waiting-for-feedback
