### ISSUE TITLE
add suport for Java Instant

### ISSUE THREAD

**Issue by crorodriguezro** [r2dbc/r2dbc-mssql#174] opened 2020-10-15 16:27 UTC
#### Is your feature request related to a problem? Please describe

When trying to save an object that contains an Instant value, I got the following error:

java.lang.IllegalArgumentException: Cannot encode [2020-10-15T16:17:51.949Z] parameter of type [java.time.Instant]
	at io.r2dbc.mssql.codec.DefaultCodecs.encode(DefaultCodecs.java:101)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):

Stack trace:
		at io.r2dbc.mssql.codec.DefaultCodecs.encode(DefaultCodecs.java:101)
.
.
.

#### Describe the solution you'd like

I would like to be able to persist Instant types. 
There is an existing codec for Insant available for postgres driver
https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/codec/InstantCodec.java

**Comment by mp911de** [comment] 2020-10-21 09:40
To which data type should `Instant` map to? The only type that would come close is `datetimeoffset` but that one leaves us with the question of what timezone to use. `Instant` a moment in time that is internally represented as epoch seconds at UTC. Storing an `Instant` via `Timestamp.from(Instant.now())` with JDBC normalizes the value into the system-default timezone and leaves the offset at zero.

**Comment by crorodriguezro** [comment] 2020-11-20 01:07
I don't know much about jdbc or r2dbc. But maybe Instant could be treated as an UTC LocalDateTime. 
What I mean is that `LocalDateTime.ofInstant(Instant.now(), ZoneOffset.UTC)` could be store the same way as `Instant.now()`

**Comment by mp911de** [comment] 2020-11-20 07:52
That doesn't sound convincing. Since we don't have a clear mapping strategy, we're closing this ticket without an implementation.

**Closed by mp911de** 2020-11-20 07:52 UTC
Labels: status: waiting-for-feedback, type: enhancement

**Comment by zdanek** [comment] 2023-08-03 11:56
Hi.
I run into this problem in my project. I can support you with relevant info, to get this done.
We need this codec as `java.time.Instant` is modern type for storing datetime when using machine-to-machine communication.

The problem is to choose which store type to use.
Use `datetimeoffset` in this case is tempting but I'd not use it. The reason is that we're aiming to store `Instant` as date time in UTC timezone only. So we have fixed TZ. Using `datetimeoffset` allows to define or put data in different timezone than UTC.

Using `datetime2` is the best approach. It does not declare TZ explicitly but here we have only one possible TZ and it's UTC.
The way `datetime2` works is taking datetime as it is, with trimming `Z` that denotes TZ. It's simply omitted. And this is what we need taking `java.time.Instant` as an input.

@mp911de 
I can provide working Codec for this but I need your approval and agreement on this.
